# Generated by Django 3.2.15 on 2023-06-17 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0118_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('date_format', models.CharField(max_length=1, verbose_name='Date Format')),
                ('is_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(verbose_name='name')),
                ('timezone', timezone_field.fields.TimeZoneField(verbose_name='Timezone')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='common.organization')),
            ],
        ),
    ]
