# Generated by Django 3.2.20 on 2023-08-29 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0119_repository_count_repository_train'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntelligence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access token')),
                ('name', models.TextField(verbose_name='name')),
                ('integrated_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligences', to='project.project')),
                ('repositories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_intelligence', to='common.repository')),
            ],
        ),
    ]
