# Generated by Django 3.2.20 on 2023-09-06 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20230830_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintelligence',
            name='integrated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_intelligences', to=settings.AUTH_USER_MODEL),
        ),
    ]
