# Generated by Django 3.2.20 on 2023-08-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectintelligence_integrated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='template_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.templatetype'),
        ),
    ]
