# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bothub/protos/inteligence/repository.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bothub/protos/inteligence/repository.proto',
  package='weni.bothub.repository',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*bothub/protos/inteligence/repository.proto\x12\x16weni.bothub.repository\"\xca\x03\n\nRepository\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04slug\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nis_private\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x10\n\x08language\x18\x07 \x01(\t\x12\r\n\x05owner\x18\x08 \x01(\x05\x12\x11\n\talgorithm\x18\t \x01(\t\x12\x1d\n\x15use_competing_intents\x18\n \x01(\x08\x12\x19\n\x11use_name_entities\x18\x0b \x01(\x08\x12\x18\n\x10use_analyze_char\x18\x0c \x01(\x08\x12\x17\n\x0frepository_type\x18\r \x01(\t\x12\x17\n\x0fowner__nickname\x18\x0e \x01(\t\x12/\n\x07intents\x18\x0f \x03(\x0b\x32\x1e.weni.bothub.repository.Intent\x12\x12\n\ncategories\x18\x10 \x03(\x05\x12\x1b\n\x13\x61vailable_languages\x18\x11 \x03(\t\x12\x39\n\x0f\x63\x61tegories_list\x18\x12 \x03(\x0b\x32 .weni.bothub.repository.Category\"<\n\x06Intent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\x17\n\x0f\x65xamples__count\x18\x03 \x01(\x05\"2\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04icon\x18\x03 \x01(\t\"E\n\x15RepositoryListRequest\x12\x13\n\x06org_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0c\n\x04name\x18\x02 \x01(\tB\t\n\x07_org_id\"J\n&RepositoryAuthorizationRetrieveRequest\x12 \n\x18repository_authorization\x18\x01 \x01(\t2\xf4\x01\n\x14RepositoryController\x12]\n\x04List\x12-.weni.bothub.repository.RepositoryListRequest\x1a\".weni.bothub.repository.Repository\"\x00\x30\x01\x12}\n\x15RetrieveAuthorization\x12>.weni.bothub.repository.RepositoryAuthorizationRetrieveRequest\x1a\".weni.bothub.repository.Repository\"\x00\x62\x06proto3'
)




_REPOSITORY = _descriptor.Descriptor(
  name='Repository',
  full_name='weni.bothub.repository.Repository',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='weni.bothub.repository.Repository.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='weni.bothub.repository.Repository.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slug', full_name='weni.bothub.repository.Repository.slug', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='weni.bothub.repository.Repository.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_private', full_name='weni.bothub.repository.Repository.is_private', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='weni.bothub.repository.Repository.created_at', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='language', full_name='weni.bothub.repository.Repository.language', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner', full_name='weni.bothub.repository.Repository.owner', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='weni.bothub.repository.Repository.algorithm', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_competing_intents', full_name='weni.bothub.repository.Repository.use_competing_intents', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_name_entities', full_name='weni.bothub.repository.Repository.use_name_entities', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_analyze_char', full_name='weni.bothub.repository.Repository.use_analyze_char', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repository_type', full_name='weni.bothub.repository.Repository.repository_type', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner__nickname', full_name='weni.bothub.repository.Repository.owner__nickname', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intents', full_name='weni.bothub.repository.Repository.intents', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categories', full_name='weni.bothub.repository.Repository.categories', index=15,
      number=16, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available_languages', full_name='weni.bothub.repository.Repository.available_languages', index=16,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categories_list', full_name='weni.bothub.repository.Repository.categories_list', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=529,
)


_INTENT = _descriptor.Descriptor(
  name='Intent',
  full_name='weni.bothub.repository.Intent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='weni.bothub.repository.Intent.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='weni.bothub.repository.Intent.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examples__count', full_name='weni.bothub.repository.Intent.examples__count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=591,
)


_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='weni.bothub.repository.Category',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='weni.bothub.repository.Category.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='weni.bothub.repository.Category.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='icon', full_name='weni.bothub.repository.Category.icon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=643,
)


_REPOSITORYLISTREQUEST = _descriptor.Descriptor(
  name='RepositoryListRequest',
  full_name='weni.bothub.repository.RepositoryListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='org_id', full_name='weni.bothub.repository.RepositoryListRequest.org_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='weni.bothub.repository.RepositoryListRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_org_id', full_name='weni.bothub.repository.RepositoryListRequest._org_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=645,
  serialized_end=714,
)


_REPOSITORYAUTHORIZATIONRETRIEVEREQUEST = _descriptor.Descriptor(
  name='RepositoryAuthorizationRetrieveRequest',
  full_name='weni.bothub.repository.RepositoryAuthorizationRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='repository_authorization', full_name='weni.bothub.repository.RepositoryAuthorizationRetrieveRequest.repository_authorization', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=790,
)

_REPOSITORY.fields_by_name['intents'].message_type = _INTENT
_REPOSITORY.fields_by_name['categories_list'].message_type = _CATEGORY
_REPOSITORYLISTREQUEST.oneofs_by_name['_org_id'].fields.append(
  _REPOSITORYLISTREQUEST.fields_by_name['org_id'])
_REPOSITORYLISTREQUEST.fields_by_name['org_id'].containing_oneof = _REPOSITORYLISTREQUEST.oneofs_by_name['_org_id']
DESCRIPTOR.message_types_by_name['Repository'] = _REPOSITORY
DESCRIPTOR.message_types_by_name['Intent'] = _INTENT
DESCRIPTOR.message_types_by_name['Category'] = _CATEGORY
DESCRIPTOR.message_types_by_name['RepositoryListRequest'] = _REPOSITORYLISTREQUEST
DESCRIPTOR.message_types_by_name['RepositoryAuthorizationRetrieveRequest'] = _REPOSITORYAUTHORIZATIONRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Repository = _reflection.GeneratedProtocolMessageType('Repository', (_message.Message,), {
  'DESCRIPTOR' : _REPOSITORY,
  '__module__' : 'bothub.protos.inteligence.repository_pb2'
  # @@protoc_insertion_point(class_scope:weni.bothub.repository.Repository)
  })
_sym_db.RegisterMessage(Repository)

Intent = _reflection.GeneratedProtocolMessageType('Intent', (_message.Message,), {
  'DESCRIPTOR' : _INTENT,
  '__module__' : 'bothub.protos.inteligence.repository_pb2'
  # @@protoc_insertion_point(class_scope:weni.bothub.repository.Intent)
  })
_sym_db.RegisterMessage(Intent)

Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'bothub.protos.inteligence.repository_pb2'
  # @@protoc_insertion_point(class_scope:weni.bothub.repository.Category)
  })
_sym_db.RegisterMessage(Category)

RepositoryListRequest = _reflection.GeneratedProtocolMessageType('RepositoryListRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPOSITORYLISTREQUEST,
  '__module__' : 'bothub.protos.inteligence.repository_pb2'
  # @@protoc_insertion_point(class_scope:weni.bothub.repository.RepositoryListRequest)
  })
_sym_db.RegisterMessage(RepositoryListRequest)

RepositoryAuthorizationRetrieveRequest = _reflection.GeneratedProtocolMessageType('RepositoryAuthorizationRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPOSITORYAUTHORIZATIONRETRIEVEREQUEST,
  '__module__' : 'bothub.protos.inteligence.repository_pb2'
  # @@protoc_insertion_point(class_scope:weni.bothub.repository.RepositoryAuthorizationRetrieveRequest)
  })
_sym_db.RegisterMessage(RepositoryAuthorizationRetrieveRequest)



_REPOSITORYCONTROLLER = _descriptor.ServiceDescriptor(
  name='RepositoryController',
  full_name='weni.bothub.repository.RepositoryController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=793,
  serialized_end=1037,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='weni.bothub.repository.RepositoryController.List',
    index=0,
    containing_service=None,
    input_type=_REPOSITORYLISTREQUEST,
    output_type=_REPOSITORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RetrieveAuthorization',
    full_name='weni.bothub.repository.RepositoryController.RetrieveAuthorization',
    index=1,
    containing_service=None,
    input_type=_REPOSITORYAUTHORIZATIONRETRIEVEREQUEST,
    output_type=_REPOSITORY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPOSITORYCONTROLLER)

DESCRIPTOR.services_by_name['RepositoryController'] = _REPOSITORYCONTROLLER

# @@protoc_insertion_point(module_scope)
