# Generated by Django 2.0.2 on 2018-06-05 13:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [("authentication", "0003_auto_20180522_1705")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                help_text="User's nickname, using letters, numbers, underscores and hyphens without spaces.",
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid 'nickname' consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="nickname",
            ),
        )
    ]
