# Generated by Django 2.2.12 on 2020-07-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180620_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's name.", max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'repository organization',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='repositoryowner_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.RepositoryOwner'),
            preserve_default=False,
        ),
    ]
