# Generated by Django 2.2.17 on 2020-11-05 22:07

import bothub.authentication.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200729_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryowner',
            name='nickname',
            field=models.CharField(help_text="User's or Organization nickname, using letters, numbers, underscores and hyphens without spaces.", max_length=150, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'nickname' consisting of letters, numbers, underscores or hyphens.", 'invalid'), bothub.authentication.models.validate_user_nickname_value], verbose_name='nickname'),
        ),
    ]
