# Generated by Django 2.2.12 on 2020-07-10 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200709_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='repositoryowner',
            name='joined_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='joined at'),
            preserve_default=False,
        ),
    ]
