# Generated by Django 2.2.12 on 2020-07-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200710_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repository_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='user_owner', to='authentication.RepositoryOwner'),
        ),
    ]
