# Generated by Django 2.2.12 on 2020-07-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
    ]
