# Generated by Django 3.2.8 on 2021-10-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210506_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryowner',
            name='name',
            field=models.CharField(help_text="User's name.", max_length=150, verbose_name='name'),
        ),
    ]
