# Generated by Django 2.2.12 on 2020-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0009_remove_user_biography")]

    operations = [
        migrations.AddField(
            model_name="repositoryowner",
            name="biography",
            field=models.TextField(blank=True, null=True, verbose_name="biography"),
        )
    ]
