# Generated by Django 2.1.11 on 2020-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0056_auto_20200512_1514")]

    operations = [
        migrations.AlterUniqueTogether(
            name="repositoryentitylabel", unique_together=set()
        ),
        migrations.RemoveField(model_name="repositoryentitylabel", name="repository"),
        migrations.DeleteModel(name="RepositoryEntityLabel"),
    ]
