# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bothub/protos/authentication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="bothub/protos/authentication.proto",
    package="authentication",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n"bothub/protos/authentication.proto\x12\x0e\x61uthentication\x1a\x1bgoogle/protobuf/empty.proto"@\n\x1dUserPermissionRetrieveRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06org_id\x18\x02 \x01(\x05"R\n\x1bUserPermissionUpdateRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\npermission\x18\x03 \x01(\x05"R\n\x1bUserPermissionRemoveRequest\x12\x0e\n\x06org_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\npermission\x18\x03 \x01(\x05"\x1a\n\nPermission\x12\x0c\n\x04role\x18\x01 \x01(\x05"$\n\x13UserRetrieveRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t"}\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tjoined_at\x18\x06 \x01(\t\x12\x11\n\tis_active\x18\x07 \x01(\x08\x12\x14\n\x0cis_superuser\x18\x08 \x01(\x08\x32\x99\x02\n\x18UserPermissionController\x12W\n\x08Retrieve\x12-.authentication.UserPermissionRetrieveRequest\x1a\x1a.authentication.Permission"\x00\x12S\n\x06Update\x12+.authentication.UserPermissionUpdateRequest\x1a\x1a.authentication.Permission"\x00\x12O\n\x06Remove\x12+.authentication.UserPermissionRemoveRequest\x1a\x16.google.protobuf.Empty"\x00\x32Y\n\x0eUserController\x12G\n\x08Retrieve\x12#.authentication.UserRetrieveRequest\x1a\x14.authentication.User"\x00\x62\x06proto3',
    dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR],
)


_USERPERMISSIONRETRIEVEREQUEST = _descriptor.Descriptor(
    name="UserPermissionRetrieveRequest",
    full_name="authentication.UserPermissionRetrieveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="authentication.UserPermissionRetrieveRequest.user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="org_id",
            full_name="authentication.UserPermissionRetrieveRequest.org_id",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=83,
    serialized_end=147,
)


_USERPERMISSIONUPDATEREQUEST = _descriptor.Descriptor(
    name="UserPermissionUpdateRequest",
    full_name="authentication.UserPermissionUpdateRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="org_id",
            full_name="authentication.UserPermissionUpdateRequest.org_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="authentication.UserPermissionUpdateRequest.user_id",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="permission",
            full_name="authentication.UserPermissionUpdateRequest.permission",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=149,
    serialized_end=231,
)


_USERPERMISSIONREMOVEREQUEST = _descriptor.Descriptor(
    name="UserPermissionRemoveRequest",
    full_name="authentication.UserPermissionRemoveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="org_id",
            full_name="authentication.UserPermissionRemoveRequest.org_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_id",
            full_name="authentication.UserPermissionRemoveRequest.user_id",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="permission",
            full_name="authentication.UserPermissionRemoveRequest.permission",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=233,
    serialized_end=315,
)


_PERMISSION = _descriptor.Descriptor(
    name="Permission",
    full_name="authentication.Permission",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="role",
            full_name="authentication.Permission.role",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=317,
    serialized_end=343,
)


_USERRETRIEVEREQUEST = _descriptor.Descriptor(
    name="UserRetrieveRequest",
    full_name="authentication.UserRetrieveRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="email",
            full_name="authentication.UserRetrieveRequest.email",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=345,
    serialized_end=381,
)


_USER = _descriptor.Descriptor(
    name="User",
    full_name="authentication.User",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="authentication.User.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="email",
            full_name="authentication.User.email",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="nickname",
            full_name="authentication.User.nickname",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="authentication.User.name",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="joined_at",
            full_name="authentication.User.joined_at",
            index=4,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_active",
            full_name="authentication.User.is_active",
            index=5,
            number=7,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="is_superuser",
            full_name="authentication.User.is_superuser",
            index=6,
            number=8,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=383,
    serialized_end=508,
)

DESCRIPTOR.message_types_by_name[
    "UserPermissionRetrieveRequest"
] = _USERPERMISSIONRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name[
    "UserPermissionUpdateRequest"
] = _USERPERMISSIONUPDATEREQUEST
DESCRIPTOR.message_types_by_name[
    "UserPermissionRemoveRequest"
] = _USERPERMISSIONREMOVEREQUEST
DESCRIPTOR.message_types_by_name["Permission"] = _PERMISSION
DESCRIPTOR.message_types_by_name["UserRetrieveRequest"] = _USERRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name["User"] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserPermissionRetrieveRequest = _reflection.GeneratedProtocolMessageType(
    "UserPermissionRetrieveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERPERMISSIONRETRIEVEREQUEST,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.UserPermissionRetrieveRequest)
    },
)
_sym_db.RegisterMessage(UserPermissionRetrieveRequest)

UserPermissionUpdateRequest = _reflection.GeneratedProtocolMessageType(
    "UserPermissionUpdateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERPERMISSIONUPDATEREQUEST,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.UserPermissionUpdateRequest)
    },
)
_sym_db.RegisterMessage(UserPermissionUpdateRequest)

UserPermissionRemoveRequest = _reflection.GeneratedProtocolMessageType(
    "UserPermissionRemoveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERPERMISSIONREMOVEREQUEST,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.UserPermissionRemoveRequest)
    },
)
_sym_db.RegisterMessage(UserPermissionRemoveRequest)

Permission = _reflection.GeneratedProtocolMessageType(
    "Permission",
    (_message.Message,),
    {
        "DESCRIPTOR": _PERMISSION,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.Permission)
    },
)
_sym_db.RegisterMessage(Permission)

UserRetrieveRequest = _reflection.GeneratedProtocolMessageType(
    "UserRetrieveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERRETRIEVEREQUEST,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.UserRetrieveRequest)
    },
)
_sym_db.RegisterMessage(UserRetrieveRequest)

User = _reflection.GeneratedProtocolMessageType(
    "User",
    (_message.Message,),
    {
        "DESCRIPTOR": _USER,
        "__module__": "bothub.protos.authentication_pb2"
        # @@protoc_insertion_point(class_scope:authentication.User)
    },
)
_sym_db.RegisterMessage(User)


_USERPERMISSIONCONTROLLER = _descriptor.ServiceDescriptor(
    name="UserPermissionController",
    full_name="authentication.UserPermissionController",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=511,
    serialized_end=792,
    methods=[
        _descriptor.MethodDescriptor(
            name="Retrieve",
            full_name="authentication.UserPermissionController.Retrieve",
            index=0,
            containing_service=None,
            input_type=_USERPERMISSIONRETRIEVEREQUEST,
            output_type=_PERMISSION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Update",
            full_name="authentication.UserPermissionController.Update",
            index=1,
            containing_service=None,
            input_type=_USERPERMISSIONUPDATEREQUEST,
            output_type=_PERMISSION,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Remove",
            full_name="authentication.UserPermissionController.Remove",
            index=2,
            containing_service=None,
            input_type=_USERPERMISSIONREMOVEREQUEST,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_USERPERMISSIONCONTROLLER)

DESCRIPTOR.services_by_name["UserPermissionController"] = _USERPERMISSIONCONTROLLER


_USERCONTROLLER = _descriptor.ServiceDescriptor(
    name="UserController",
    full_name="authentication.UserController",
    file=DESCRIPTOR,
    index=1,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=794,
    serialized_end=883,
    methods=[
        _descriptor.MethodDescriptor(
            name="Retrieve",
            full_name="authentication.UserController.Retrieve",
            index=0,
            containing_service=None,
            input_type=_USERRETRIEVEREQUEST,
            output_type=_USER,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        )
    ],
)
_sym_db.RegisterServiceDescriptor(_USERCONTROLLER)

DESCRIPTOR.services_by_name["UserController"] = _USERCONTROLLER

# @@protoc_insertion_point(module_scope)
