# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bothub/protos/organization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="bothub/protos/organization.proto",
    package="org",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n bothub/protos/organization.proto\x12\x03org\x1a\x1bgoogle/protobuf/empty.proto":\n\x03Org\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x05users\x18\x03 \x03(\x0b\x32\n.org.Users"f\n\x05Users\x12\x13\n\x0borg_user_id\x18\x01 \x01(\x05\x12\x16\n\x0eorg_user_email\x18\x02 \x01(\t\x12\x19\n\x11org_user_nickname\x18\x03 \x01(\t\x12\x15\n\rorg_user_name\x18\x04 \x01(\t"$\n\x0eOrgListRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t"4\n\x10OrgCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t"3\n\x11OrgDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nuser_email\x18\x02 \x01(\t"N\n\x10OrgUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name2\xde\x01\n\rOrgController\x12)\n\x04List\x12\x13.org.OrgListRequest\x1a\x08.org.Org"\x00\x30\x01\x12+\n\x06\x43reate\x12\x15.org.OrgCreateRequest\x1a\x08.org.Org"\x00\x12\x38\n\x06Update\x12\x15.org.OrgUpdateRequest\x1a\x15.org.OrgUpdateRequest"\x00\x12;\n\x07\x44\x65stroy\x12\x16.org.OrgDestroyRequest\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3',
    dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR],
)


_ORG = _descriptor.Descriptor(
    name="Org",
    full_name="org.Org",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="org.Org.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="org.Org.name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="users",
            full_name="org.Org.users",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=70,
    serialized_end=128,
)


_USERS = _descriptor.Descriptor(
    name="Users",
    full_name="org.Users",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="org_user_id",
            full_name="org.Users.org_user_id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="org_user_email",
            full_name="org.Users.org_user_email",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="org_user_nickname",
            full_name="org.Users.org_user_nickname",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="org_user_name",
            full_name="org.Users.org_user_name",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=130,
    serialized_end=232,
)


_ORGLISTREQUEST = _descriptor.Descriptor(
    name="OrgListRequest",
    full_name="org.OrgListRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="user_email",
            full_name="org.OrgListRequest.user_email",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=234,
    serialized_end=270,
)


_ORGCREATEREQUEST = _descriptor.Descriptor(
    name="OrgCreateRequest",
    full_name="org.OrgCreateRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="org.OrgCreateRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_email",
            full_name="org.OrgCreateRequest.user_email",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=272,
    serialized_end=324,
)


_ORGDESTROYREQUEST = _descriptor.Descriptor(
    name="OrgDestroyRequest",
    full_name="org.OrgDestroyRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="org.OrgDestroyRequest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_email",
            full_name="org.OrgDestroyRequest.user_email",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=326,
    serialized_end=377,
)


_ORGUPDATEREQUEST = _descriptor.Descriptor(
    name="OrgUpdateRequest",
    full_name="org.OrgUpdateRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="org.OrgUpdateRequest.id",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_email",
            full_name="org.OrgUpdateRequest.user_email",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="org.OrgUpdateRequest.name",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="_name",
            full_name="org.OrgUpdateRequest._name",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        )
    ],
    serialized_start=379,
    serialized_end=457,
)

_ORG.fields_by_name["users"].message_type = _USERS
_ORGUPDATEREQUEST.oneofs_by_name["_name"].fields.append(
    _ORGUPDATEREQUEST.fields_by_name["name"]
)
_ORGUPDATEREQUEST.fields_by_name[
    "name"
].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name["_name"]
DESCRIPTOR.message_types_by_name["Org"] = _ORG
DESCRIPTOR.message_types_by_name["Users"] = _USERS
DESCRIPTOR.message_types_by_name["OrgListRequest"] = _ORGLISTREQUEST
DESCRIPTOR.message_types_by_name["OrgCreateRequest"] = _ORGCREATEREQUEST
DESCRIPTOR.message_types_by_name["OrgDestroyRequest"] = _ORGDESTROYREQUEST
DESCRIPTOR.message_types_by_name["OrgUpdateRequest"] = _ORGUPDATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Org = _reflection.GeneratedProtocolMessageType(
    "Org",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORG,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.Org)
    },
)
_sym_db.RegisterMessage(Org)

Users = _reflection.GeneratedProtocolMessageType(
    "Users",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERS,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.Users)
    },
)
_sym_db.RegisterMessage(Users)

OrgListRequest = _reflection.GeneratedProtocolMessageType(
    "OrgListRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORGLISTREQUEST,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.OrgListRequest)
    },
)
_sym_db.RegisterMessage(OrgListRequest)

OrgCreateRequest = _reflection.GeneratedProtocolMessageType(
    "OrgCreateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORGCREATEREQUEST,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.OrgCreateRequest)
    },
)
_sym_db.RegisterMessage(OrgCreateRequest)

OrgDestroyRequest = _reflection.GeneratedProtocolMessageType(
    "OrgDestroyRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORGDESTROYREQUEST,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.OrgDestroyRequest)
    },
)
_sym_db.RegisterMessage(OrgDestroyRequest)

OrgUpdateRequest = _reflection.GeneratedProtocolMessageType(
    "OrgUpdateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORGUPDATEREQUEST,
        "__module__": "bothub.protos.organization_pb2"
        # @@protoc_insertion_point(class_scope:org.OrgUpdateRequest)
    },
)
_sym_db.RegisterMessage(OrgUpdateRequest)


_ORGCONTROLLER = _descriptor.ServiceDescriptor(
    name="OrgController",
    full_name="org.OrgController",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=460,
    serialized_end=682,
    methods=[
        _descriptor.MethodDescriptor(
            name="List",
            full_name="org.OrgController.List",
            index=0,
            containing_service=None,
            input_type=_ORGLISTREQUEST,
            output_type=_ORG,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Create",
            full_name="org.OrgController.Create",
            index=1,
            containing_service=None,
            input_type=_ORGCREATEREQUEST,
            output_type=_ORG,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Update",
            full_name="org.OrgController.Update",
            index=2,
            containing_service=None,
            input_type=_ORGUPDATEREQUEST,
            output_type=_ORGUPDATEREQUEST,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Destroy",
            full_name="org.OrgController.Destroy",
            index=3,
            containing_service=None,
            input_type=_ORGDESTROYREQUEST,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ORGCONTROLLER)

DESCRIPTOR.services_by_name["OrgController"] = _ORGCONTROLLER

# @@protoc_insertion_point(module_scope)
