# Generated by Django 2.1.11 on 2019-12-09 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryversionlanguage',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='last update'),
            preserve_default=False,
        ),
    ]
