# Generated by Django 2.0.2 on 2018-03-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTranslatedExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French'), ('it', 'Italian'), ('nl', 'Dutch')], max_length=2, verbose_name='language')),
                ('text', models.TextField(verbose_name='text')),
                ('original_example', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.RepositoryExample')),
            ],
            options={
                'verbose_name': 'repository translated example',
                'verbose_name_plural': 'repository translated examples',
            },
        ),
        migrations.CreateModel(
            name='RepositoryTranslatedExampleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(verbose_name='start')),
                ('end', models.PositiveIntegerField(verbose_name='end')),
                ('entity', models.CharField(max_length=64, verbose_name='entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('repository_translated_example', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='common.RepositoryTranslatedExample')),
            ],
            options={
                'verbose_name': 'repository example entity',
                'verbose_name_plural': 'repository example entities',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='repositorycategory',
            options={'verbose_name': 'repository category', 'verbose_name_plural': 'repository categories'},
        ),
    ]
