# Generated by Django 2.2.12 on 2020-07-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200716_1203'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='repositoryowner_ptr',
        ),
        migrations.AddField(
            model_name='organization',
            name='repository_owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organization_owner', serialize=False, to='authentication.RepositoryOwner'),
            preserve_default=False,
        ),
    ]
