# Generated by Django 2.0.2 on 2018-02-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180225_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryexample',
            name='repository_update',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='added', to='common.RepositoryUpdate'),
            preserve_default=False,
        ),
    ]
