# Generated by Django 2.1.11 on 2019-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_repositoryversionlanguage_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='total_updates',
        ),
        migrations.AddField(
            model_name='repositoryversionlanguage',
            name='total_training_end',
            field=models.IntegerField(default=0, verbose_name='total training end'),
        ),
    ]
