# Generated by Django 2.0.2 on 2018-03-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180307_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repositorytranslatedexample',
            unique_together={('original_example', 'language')},
        ),
    ]
