# Generated by Django 2.0.2 on 2018-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180307_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, verbose_name='slug'),
        ),
    ]
