# Generated by Django 2.0.2 on 2018-02-26 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180225_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryexample',
            name='deleted_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted', to='common.RepositoryUpdate'),
        ),
        migrations.AlterField(
            model_name='repositoryexample',
            name='intent',
            field=models.CharField(blank=True, max_length=64, verbose_name='intent'),
        ),
        migrations.AlterField(
            model_name='repositoryexample',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='repositoryexampleentity',
            name='end',
            field=models.PositiveIntegerField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='repositoryexampleentity',
            name='entity',
            field=models.CharField(max_length=64, verbose_name='entity'),
        ),
        migrations.AlterField(
            model_name='repositoryexampleentity',
            name='start',
            field=models.PositiveIntegerField(verbose_name='start'),
        ),
    ]
