# Generated by Django 2.0.2 on 2018-05-15 20:19

from django.db import migrations, models
import django.db.models.deletion


def set_repository_update(apps, schema_editor):
    RepositoryTranslatedExample = apps.get_model('common', 'RepositoryTranslatedExample')
    for translate in RepositoryTranslatedExample.objects.all().iterator():
        translate.repository_update = translate.original_example.repository_update
        translate.save()

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180514_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorytranslatedexample',
            name='repository_update',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_added', to='common.RepositoryUpdate'),
        ),
        migrations.RunPython(set_repository_update),
        migrations.AlterField(
            model_name='repositorytranslatedexample',
            name='repository_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translated_added', to='common.RepositoryUpdate'),
        ),
    ]
