# Generated by Django 2.0.2 on 2018-05-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("common", "0006_repositoryupdate_failed_at")]

    operations = [
        migrations.AddField(
            model_name="repositorytranslatedexample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        )
    ]
