# Generated by Django 2.0.2 on 2018-06-11 11:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [("common", "0009_auto_20180601_1348")]

    operations = [
        migrations.AlterField(
            model_name="repositoryexample",
            name="intent",
            field=models.CharField(
                blank=True,
                help_text="Example intent reference",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9_]+\\Z"),
                        "Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="intent",
            ),
        ),
        migrations.AlterField(
            model_name="repositoryexampleentity",
            name="entity",
            field=models.CharField(
                help_text="Entity name",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9_]+\\Z"),
                        "Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="entity",
            ),
        ),
        migrations.AlterField(
            model_name="repositorytranslatedexampleentity",
            name="entity",
            field=models.CharField(
                help_text="Entity name",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-z0-9_]+\\Z"),
                        "Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="entity",
            ),
        ),
    ]
