# Generated by Django 2.0.6 on 2018-07-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0012_auto_20180703_1931")]

    operations = [
        migrations.AlterField(
            model_name="repositoryauthorization",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorizations",
                to="common.Repository",
            ),
        )
    ]
