# Generated by Django 2.0.6 on 2018-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0023_repository_use_language_model_featurizer")]

    operations = [
        migrations.AddField(
            model_name="repositoryupdate",
            name="use_language_model_featurizer",
            field=models.BooleanField(default=True),
        )
    ]
