# Generated by Django 2.1.2 on 2018-10-10 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0025_auto_20181003_1911")]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
