# Generated by Django 2.1.3 on 2019-01-21 12:50

from django.db import migrations, models


def populate_algorithm(apps, *args):
    from bothub.common.models import Repository as R
    Repository = apps.get_model('common', 'Repository')
    for repository in Repository.objects.all():
        repository.algorithm = R.ALGORITHM_NEURAL_NETWORK_EXTERNAL \
            if repository.use_language_model_featurizer else \
            R.ALGORITHM_NEURAL_NETWORK_INTERNAL
        repository.save(update_fields=['algorithm'])
        for update in repository.updates.all():
            update.algorithm = R.ALGORITHM_NEURAL_NETWORK_EXTERNAL \
                if update.use_language_model_featurizer else \
                R.ALGORITHM_NEURAL_NETWORK_INTERNAL
            update.save(update_fields=['algorithm'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_repositorycategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='algorithm',
            field=models.CharField(choices=[('statistical_model', 'Statistical Model'), ('neural_network_internal', 'Neural Network with internal vocabulary'), ('neural_network_external', 'Neural Network with external vocabulary (BETA)')], default='statistical_model', max_length=24, verbose_name='algorithm'),
        ),
        migrations.AddField(
            model_name='repositoryupdate',
            name='algorithm',
            field=models.CharField(choices=[('statistical_model', 'Statistical Model'), ('neural_network_internal', 'Neural Network with internal vocabulary'), ('neural_network_external', 'Neural Network with external vocabulary (BETA)')], default='statistical_model', max_length=24, verbose_name='algorithm'),
        ),
        migrations.RunPython(populate_algorithm),
        migrations.RemoveField(
            model_name='repository',
            name='use_language_model_featurizer',
        ),
        migrations.RemoveField(
            model_name='repositoryupdate',
            name='use_language_model_featurizer',
        ),
    ]
