# Generated by Django 2.1.5 on 2019-01-26 02:47

from django.db import migrations


def populate_algorithm(apps, *args):
    from bothub.common.models import Repository as R
    Repository = apps.get_model('common', 'Repository')
    for repository in Repository.objects.all():
        repository.algorithm = R.ALGORITHM_NEURAL_NETWORK_EXTERNAL \
            if repository.use_language_model_featurizer else \
            R.ALGORITHM_NEURAL_NETWORK_INTERNAL
        repository.save(update_fields=['algorithm'])
        for update in repository.updates.all():
            update.algorithm = R.ALGORITHM_NEURAL_NETWORK_EXTERNAL \
                if update.use_language_model_featurizer else \
                R.ALGORITHM_NEURAL_NETWORK_INTERNAL
            update.save(update_fields=['algorithm'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20190121_1250'),
    ]

    operations = [
        migrations.RunPython(populate_algorithm),
        migrations.RemoveField(
            model_name='repository',
            name='use_language_model_featurizer',
        ),
        migrations.RemoveField(
            model_name='repositoryupdate',
            name='use_language_model_featurizer',
        ),
    ]

