# Generated by Django 2.1.5 on 2019-03-18 15:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20190126_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTestingQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Testing query text', verbose_name='text')),
                ('intent', models.CharField(default='no_intent', help_text='Testing query intent reference', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-z0-9_]+\\Z'), 'Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'repository testing query',
                'verbose_name_plural': 'repository testing queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
