# Generated by Django 2.1.5 on 2019-04-03 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20190327_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Validation test text', verbose_name='text')),
                ('intent', models.CharField(default='no_intent', help_text='Validation intent reference', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-z0-9_]+\\Z'), 'Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_validation', to='common.RepositoryUpdate')),
                ('repository_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='added_validation', to='common.RepositoryUpdate')),
            ],
            options={
                'verbose_name': 'repository validation test',
                'verbose_name_plural': 'repository validation tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryValidationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(help_text='Start index of entity value in example text', verbose_name='start')),
                ('end', models.PositiveIntegerField(help_text='End index of entity value in example text', verbose_name='end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.RepositoryEntity')),
                ('repository_validation', models.ForeignKey(editable=False, help_text='Validation object', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='common.RepositoryValidation')),
            ],
            options={
                'verbose_name': 'repository example entity',
                'verbose_name_plural': 'repository example entities',
                'abstract': False,
            },
        ),
    ]
