# Generated by Django 2.1.5 on 2019-03-20 14:14

import bothub.common.languages
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_repositorytestingquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTranslatedValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Translation language', max_length=5, validators=[bothub.common.languages.validate_language], verbose_name='language')),
                ('text', models.TextField(help_text='Translation text', verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'repository translated validation',
                'verbose_name_plural': 'repository translated validations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Validation test text', verbose_name='text')),
                ('intent', models.CharField(default='no_intent', help_text='Validation intent reference', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-z0-9_]+\\Z'), 'Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='intent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('deleted_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_validation', to='common.RepositoryUpdate')),
                ('repository_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='added_validation', to='common.RepositoryUpdate')),
            ],
            options={
                'verbose_name': 'repository validation test',
                'verbose_name_plural': 'repository validation tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RepositoryTestingQuery',
        ),
        migrations.AddField(
            model_name='repositorytranslatedvalidation',
            name='original_validation',
            field=models.ForeignKey(editable=False, help_text='Validation object', on_delete=django.db.models.deletion.CASCADE, related_name='translated_validations', to='common.RepositoryValidation'),
        ),
        migrations.AddField(
            model_name='repositorytranslatedvalidation',
            name='repository_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translated_validation_added', to='common.RepositoryUpdate'),
        ),
        migrations.AlterUniqueTogether(
            name='repositorytranslatedvalidation',
            unique_together={('original_validation', 'language')},
        ),
    ]
