# Generated by Django 2.1.5 on 2019-07-02 14:19

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20190502_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryvote',
            name='vote',
        ),
        migrations.AddField(
            model_name='repositoryvote',
            name='created',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, editable=False),
        ),
    ]
