# Generated by Django 2.1.5 on 2019-03-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20190320_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTranslatedValidationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(help_text='Start index of entity value in example text', verbose_name='start')),
                ('end', models.PositiveIntegerField(help_text='End index of entity value in example text', verbose_name='end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.RepositoryEntity')),
                ('repository_translated_validation', models.ForeignKey(editable=False, help_text='Translated validation object', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='common.RepositoryTranslatedValidation')),
            ],
            options={
                'verbose_name': 'repository example entity',
                'verbose_name_plural': 'repository example entities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryValidationEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(help_text='Start index of entity value in example text', verbose_name='start')),
                ('end', models.PositiveIntegerField(help_text='End index of entity value in example text', verbose_name='end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.RepositoryEntity')),
                ('repository_example', models.ForeignKey(editable=False, help_text='Validation object', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='common.RepositoryValidation')),
            ],
            options={
                'verbose_name': 'repository example entity',
                'verbose_name_plural': 'repository example entities',
                'abstract': False,
            },
        ),
    ]
