# Generated by Django 2.1.5 on 2019-04-29 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_repositoryevaluate_repositoryevaluateentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryEvaluateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_chart', models.URLField(verbose_name='Intenties chart')),
                ('entity_chart', models.URLField(verbose_name='Entities chart')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'evaluate results',
                'verbose_name_plural': 'evaluate results',
                'db_table': 'common_repository_evaluate_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryEvaluateResultEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entity_results', to='common.RepositoryEntity')),
                ('evaluate_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate_result_entity', to='common.RepositoryEvaluateResult')),
            ],
            options={
                'db_table': 'common_repository_evaluate_result_entity',
            },
        ),
        migrations.CreateModel(
            name='RepositoryEvaluateResultIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(help_text='Evaluate intent reference', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-z0-9_]+\\Z'), 'Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='intent')),
                ('evaluate_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate_result_intent', to='common.RepositoryEvaluateResult')),
            ],
            options={
                'db_table': 'common_repository_evaluate_result_intent',
            },
        ),
        migrations.CreateModel(
            name='RepositoryEvaluationResultScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=2, max_digits=3)),
                ('f1_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=3)),
                ('recall', models.DecimalField(decimal_places=2, max_digits=3)),
                ('support', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'db_table': 'common_repository_evaluate_result_score',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='repositoryevaluateresultintent',
            name='score',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_intenties_score', to='common.RepositoryEvaluationResultScore'),
        ),
        migrations.AddField(
            model_name='repositoryevaluateresultentity',
            name='score',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_entities_score', to='common.RepositoryEvaluationResultScore'),
        ),
        migrations.AddField(
            model_name='repositoryevaluateresult',
            name='entity_results',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entity_results', to='common.RepositoryEvaluationResultScore'),
        ),
        migrations.AddField(
            model_name='repositoryevaluateresult',
            name='intent_results',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='intent_results', to='common.RepositoryEvaluationResultScore'),
        ),
        migrations.AddField(
            model_name='repositoryevaluateresult',
            name='repository_evaluate',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='common.RepositoryEvaluate'),
        ),
    ]
