# Generated by Django 2.1.5 on 2019-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20190430_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryevaluateresult',
            name='version',
            field=models.IntegerField(default=0, editable=False, verbose_name='Version'),
        ),
    ]
