# Generated by Django 2.1.5 on 2019-03-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_repositorytranslatedvalidationentity_repositoryvalidationentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositoryvalidationentity',
            old_name='repository_example',
            new_name='repository_validation',
        ),
    ]
