# Generated by Django 2.1.5 on 2019-08-16 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_repository_total_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryvote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
