# Generated by Django 2.1.5 on 2019-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20190816_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='nlp_server',
            field=models.URLField(blank=True, null=True, verbose_name='Base URL NLP'),
        ),
    ]
