# Generated by Django 2.1.5 on 2019-07-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0033_auto_20190702_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMigrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrate', to='common.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_migrate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'repository migrate',
                'verbose_name_plural': 'repository migrates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='repositorymigrate',
            unique_together={('user', 'repository')},
        ),
    ]
