# Generated by Django 2.1.5 on 2019-07-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20190702_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryvote',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
