# Generated by Django 2.1.5 on 2019-03-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20190320_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorytranslatedvalidation',
            name='original_validation',
            field=models.ForeignKey(editable=False, help_text='Validation object', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='common.RepositoryValidation'),
        ),
    ]
