# Generated by Django 2.1.5 on 2019-09-02 14:55
from django.conf import settings
from django.db import migrations, models
from bothub.utils import send_bot_data_file_aws
from bothub.common.models import RepositoryUpdate


def update_repository(apps, schema_editor):
    if settings.AWS_SEND:
        for update in RepositoryUpdate.objects.all().exclude(bot_data__exact=''):
            repository_update = RepositoryUpdate.objects.get(pk=update.pk)
            bot_data = send_bot_data_file_aws(update.pk, update.bot_data)
            repository_update.bot_data = bot_data
            repository_update.save(
                update_fields=[
                    'bot_data',
                ])
            print('Updating bot_data repository_update {}'.format(str(update.pk)))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_repository_nlp_server'),
    ]

    operations = [
        migrations.RunPython(update_repository),
        migrations.AlterField(
            model_name='repositoryupdate',
            name='bot_data',
            field=models.TextField(blank=True, verbose_name='bot data'),
        ),
    ]
