# Generated by Django 2.1.5 on 2019-03-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20190320_1503'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repositorytranslatedvalidation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='repositorytranslatedvalidation',
            name='original_validation',
        ),
        migrations.RemoveField(
            model_name='repositorytranslatedvalidation',
            name='repository_update',
        ),
        migrations.RemoveField(
            model_name='repositorytranslatedvalidationentity',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='repositorytranslatedvalidationentity',
            name='repository_translated_validation',
        ),
        migrations.DeleteModel(
            name='RepositoryTranslatedValidation',
        ),
        migrations.DeleteModel(
            name='RepositoryTranslatedValidationEntity',
        ),
    ]
