# Generated by Django 2.1.5 on 2019-07-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20190709_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorymigrate',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='migrate', to='common.Repository'),
        ),
    ]
