# Generated by Django 2.1.5 on 2019-09-02 14:55

from django.db import migrations, models
from bothub.utils import send_bot_data_file_aws
from bothub.common.models import RepositoryUpdate


def update_repository(apps, schema_editor):
    for update in RepositoryUpdate.objects.all().exclude(bot_data__exact=''):
        url = send_bot_data_file_aws(update.pk, update.bot_data)
        repository_update = RepositoryUpdate.objects.get(pk=update.pk)
        repository_update.bot_data = url
        repository_update.save(
            update_fields=[
                'bot_data',
            ])
        print('Updating bot_data repository_update {}'.format(str(update.pk)))


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_repository_nlp_server'),
    ]

    operations = [
        migrations.RunPython(update_repository),
        migrations.AlterField(
            model_name='repositoryupdate',
            name='bot_data',
            field=models.URLField(blank=True, verbose_name='bot data'),
        ),
    ]
