# Generated by Django 2.1.5 on 2019-07-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_auto_20190717_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repositorymigrate',
            unique_together=set(),
        ),
    ]
