# Generated by Django 2.1.11 on 2019-09-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_usergrouprepository_userpermissionrepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryauthorization',
            name='usergrouprepository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.UserGroupRepository'),
        ),
    ]
