# Generated by Django 2.1.5 on 2019-07-18 13:38

import bothub.common.languages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20190718_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorymigrate',
            name='language',
            field=models.CharField(default='en', max_length=5, validators=[bothub.common.languages.validate_language], verbose_name='language'),
            preserve_default=False,
        ),
    ]
