# Generated by Django 2.1.11 on 2019-10-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20191002_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryauthorization',
            name='role',
        ),
    ]
