# Generated by Django 2.1.11 on 2019-10-11 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0032_repository_total_updates")]

    operations = [
        migrations.RemoveField(model_name="repositoryvote", name="vote"),
        migrations.AddField(
            model_name="repository",
            name="nlp_server",
            field=models.URLField(blank=True, null=True, verbose_name="Base URL NLP"),
        ),
        migrations.AddField(
            model_name="repositoryvote",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="repositoryupdate",
            name="bot_data",
            field=models.TextField(blank=True, verbose_name="bot data"),
        ),
    ]
