# Generated by Django 2.1.11 on 2019-10-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0037_remove_repositoryauthorization_role")]

    operations = [
        migrations.AddField(
            model_name="usergrouprepository",
            name="standard",
            field=models.BooleanField(default=True),
        )
    ]
