# Generated by Django 2.1.11 on 2019-09-30 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_repositoryauthorization_usergrouprepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('codename', models.TextField(verbose_name='CodeName')),
            ],
            options={
                'verbose_name': 'permissions code',
            },
        ),
        migrations.AlterField(
            model_name='userpermissionrepository',
            name='codename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.PermissionsCode'),
        ),
    ]
