# Generated by Django 2.1.11 on 2019-10-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0038_usergrouprepository_standard")]

    operations = [
        migrations.AlterModelOptions(
            name="userpermissionrepository",
            options={"verbose_name": "User Permission Repository"},
        )
    ]
