# Generated by Django 2.1.11 on 2019-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_auto_20190930_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionrepository',
            name='name',
        ),
        migrations.AddField(
            model_name='permissionscode',
            name='name',
            field=models.TextField(null=True, verbose_name='Name'),
        ),
    ]
