# Generated by Django 2.1.11 on 2019-11-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0039_auto_20191114_2018")]

    operations = [
        migrations.AddField(
            model_name="repositoryupdate",
            name="publish",
            field=models.BooleanField(default=False),
        )
    ]
