# Generated by Django 2.1.11 on 2019-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_auto_20190930_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionscode',
            name='uuid',
        ),
        migrations.AddField(
            model_name='permissionscode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
