# Generated by Django 2.1.11 on 2019-12-05 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("common", "0039_auto_20191114_2018")]

    operations = [
        migrations.AddField(
            model_name="repositoryupdate",
            name="last_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="bot data"
            ),
            preserve_default=False,
        )
    ]
