# Generated by Django 2.1.11 on 2019-12-05 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("common", "0040_repositoryupdate_last_update")]

    operations = [
        migrations.AddField(
            model_name="repositoryexample",
            name="last_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last update"
            ),
            preserve_default=False,
        )
    ]
