# Generated by Django 2.1.11 on 2019-09-30 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_auto_20190930_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionscode',
            name='id',
        ),
        migrations.AddField(
            model_name='permissionscode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
