# Generated by Django 2.1.11 on 2019-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0041_repositoryexample_last_update")]

    operations = [
        migrations.AlterField(
            model_name="repositoryupdate",
            name="last_update",
            field=models.DateTimeField(verbose_name="last update"),
        )
    ]
