# Generated by Django 2.1.11 on 2019-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_auto_20191212_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryversionlanguage',
            name='last_update',
            field=models.DateTimeField(verbose_name='last update'),
        ),
    ]
