# Generated by Django 2.1.11 on 2019-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_auto_20191212_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryversionlanguage',
            name='last_update',
            field=models.DateTimeField(null=True, verbose_name='last update'),
        ),
    ]
