# Generated by Django 2.1.11 on 2019-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0042_auto_20191205_1221")]

    operations = [
        migrations.AlterField(
            model_name="repositoryupdate",
            name="last_update",
            field=models.DateTimeField(auto_now_add=True, verbose_name="last update"),
        )
    ]
