# Generated by Django 2.1.11 on 2019-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0043_auto_20191205_1227")]

    operations = [
        migrations.AddField(
            model_name="repositoryupdate",
            name="selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryupdate",
            name="version",
            field=models.BooleanField(default=False),
        ),
    ]
