# Generated by Django 2.1.11 on 2019-12-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0043_migrate_all_train_for_versioning")]

    operations = [
        migrations.RemoveField(model_name="repositoryupdate", name="by"),
        migrations.RemoveField(model_name="repositoryupdate", name="repository"),
        migrations.RemoveField(model_name="repository", name="total_updates"),
        migrations.RemoveField(
            model_name="repositoryevaluate", name="repository_update"
        ),
        migrations.RemoveField(
            model_name="repositoryevaluateresult", name="repository_update"
        ),
        migrations.RemoveField(model_name="repositoryexample", name="deleted_in"),
        migrations.RemoveField(
            model_name="repositoryexample", name="repository_update"
        ),
        migrations.RemoveField(
            model_name="repositorytranslatedexample", name="repository_update"
        ),
        migrations.AlterField(
            model_name="repositoryevaluate",
            name="deleted_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_evaluate",
                to="common.RepositoryVersionLanguage",
            ),
        ),
        migrations.DeleteModel(name="RepositoryUpdate"),
    ]
