# Generated by Django 2.1.11 on 2019-12-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0044_auto_20191205_1310")]

    operations = [migrations.RemoveField(model_name="repositoryupdate", name="version")]
