# Generated by Django 2.1.11 on 2019-12-26 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0044_auto_20191217_1414"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryNLPLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Text")),
                ("user_agent", models.TextField(help_text="User Agent")),
                ("nlp_log", models.TextField(blank=True, help_text="NLP Log")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "repository_version_language",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nlp_logs",
                        to="common.RepositoryVersionLanguage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "repository nlp logs"},
        ),
        migrations.CreateModel(
            name="RepositoryNLPLogIntent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.TextField(help_text="Intent")),
                ("confidence", models.FloatField(help_text="Confidence")),
                (
                    "is_default",
                    models.BooleanField(help_text="is default, intent selected"),
                ),
                (
                    "repository_nlp_log",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.RepositoryNLPLog",
                    ),
                ),
            ],
            options={"verbose_name": "repository nlp logs intent"},
        ),
    ]
