# Generated by Django 2.1.11 on 2020-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0045_repositorynlplog_repositorynlplogintent")]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("statistical_model", "Statistical Model"),
                    (
                        "neural_network_internal",
                        "Neural Network with internal vocabulary",
                    ),
                    (
                        "neural_network_external",
                        "Neural Network with external vocabulary (BETA)",
                    ),
                ],
                default="neural_network_internal",
                max_length=24,
                verbose_name="algorithm",
            ),
        )
    ]
