# Generated by Django 2.1.11 on 2019-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0045_remove_repositoryupdate_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryupdate',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
