# Generated by Django 2.1.11 on 2020-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0047_auto_20200310_1648")]

    operations = [
        migrations.AddField(
            model_name="repositorynlplog",
            name="from_backend",
            field=models.BooleanField(default=True),
            preserve_default=False,
        )
    ]
