# Generated by Django 2.1.11 on 2020-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0048_repositorynlplog_from_backend")]

    operations = [
        migrations.AddField(
            model_name="repositoryexample",
            name="is_corrected",
            field=models.BooleanField(default=False),
        )
    ]
