# Generated by Django 2.1.11 on 2020-04-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0052_delete_evaluates_isdeleted")]

    operations = [
        migrations.RemoveField(model_name="repositoryevaluate", name="deleted_in")
    ]
