# Generated by Django 2.1.11 on 2020-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0053_remove_repositoryevaluate_deleted_in")]

    operations = [
        migrations.AddField(
            model_name="repositoryversion",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        )
    ]
