# Generated by Django 2.1.11 on 2020-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0054_repositoryversion_is_deleted")]

    operations = [
        migrations.AddField(
            model_name="repositoryevaluateresult",
            name="log_entities",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Evaluate Entities Log"
            ),
        ),
        migrations.AlterField(
            model_name="repositoryevaluateresult",
            name="log",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Evaluate Intents Log"
            ),
        ),
    ]
