# Generated by Django 2.1.11 on 2020-05-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0055_auto_20200518_1810")]

    operations = [
        migrations.CreateModel(
            name="RepositoryNLPTrain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_data", models.TextField(blank=True, verbose_name="bot data")),
                (
                    "rasa_version",
                    models.CharField(max_length=20, verbose_name="Rasa Version Code"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={"verbose_name": "repository nlp train"},
        ),
        migrations.AddField(
            model_name="repositorynlptrain",
            name="repositoryversionlanguage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainers",
                to="common.RepositoryVersionLanguage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repositorynlptrain",
            unique_together={("repositoryversionlanguage", "rasa_version")},
        ),
    ]
