# Generated by Django 2.1.11 on 2020-05-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0057_migrate_trainers")]

    operations = [
        migrations.AlterField(
            model_name="repositorynlplogintent",
            name="repository_nlp_log",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repository_nlp_log",
                to="common.RepositoryNLPLog",
            ),
        )
    ]
