# Generated by Django 2.1.11 on 2020-05-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_auto_20200522_1522'),
        ('common', '0058_auto_20200520_1257'),
    ]

    operations = [
    ]
