# Generated by Django 2.1.11 on 2020-05-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_auto_20200513_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryentity',
            name='repository',
        ),
    ]
