# Generated by Django 2.1.11 on 2020-05-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0060_migrate_labels")]

    operations = [
        migrations.RemoveField(model_name="repositoryentitylabel", name="repository"),
        migrations.RemoveField(model_name="repositoryentity", name="label"),
        migrations.RemoveField(model_name="repositoryentity", name="repository"),
        migrations.DeleteModel(name="RepositoryEntityLabel"),
    ]
