# Generated by Django 2.1.11 on 2020-05-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0060_remove_repositoryentity_repository"),
        ("common", "0055_auto_20200518_0951"),
    ]

    operations = []
