# Generated by Django 2.1.11 on 2020-05-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0061_merge_20200518_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositoryentity',
            old_name='label',
            new_name='group',
        ),
    ]
