# Generated by Django 2.2.12 on 2020-06-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0062_fix_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryQueueTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_queue', models.TextField(verbose_name='id queue')),
                ('from_queue', models.PositiveIntegerField(choices=[(0, 'Ai Platform'), (1, 'Celery NLU Worker')], default=1, verbose_name='From Queue NLP')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Success')], default=1, verbose_name='Status Queue NLP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('repositoryversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='common.RepositoryVersion')),
            ],
            options={
                'verbose_name': 'repository nlp queue train',
                'unique_together': {('repositoryversion', 'id_queue')},
            },
        ),
    ]
