# Generated by Django 2.2.12 on 2020-06-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0062_fix_entities")]

    operations = [
        migrations.CreateModel(
            name="RepositoryQueueTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_queue", models.TextField(verbose_name="id queue")),
                (
                    "from_queue",
                    models.PositiveIntegerField(
                        choices=[(0, "Ai Platform"), (1, "Celery NLU Worker")],
                        default=1,
                        verbose_name="From Queue NLP",
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Success"),
                            (2, "Training"),
                            (3, "Failed"),
                        ],
                        default=0,
                        verbose_name="Status Queue NLP",
                    ),
                ),
                (
                    "ml_units",
                    models.FloatField(
                        default=0, verbose_name="Machine Learning Units AiPlatform"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "end_training",
                    models.DateTimeField(null=True, verbose_name="end training"),
                ),
                (
                    "repositoryversionlanguage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="common.RepositoryVersionLanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository nlp queue train",
                "unique_together": {("repositoryversionlanguage",)},
            },
        )
    ]
