# Generated by Django 2.1.11 on 2020-05-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0055_auto_20200518_1810"),
        ("common", "0064_auto_20200518_1024"),
    ]

    operations = []
