# Generated by Django 2.2.12 on 2020-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0064_auto_20200616_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryqueuetask',
            name='id_queue',
            field=models.TextField(null=True, verbose_name='id queue'),
        ),
        migrations.AlterField(
            model_name='repositoryqueuetask',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Training'), (3, 'Failed')], default=1, verbose_name='Status Queue NLP'),
        ),
    ]
