# Generated by Django 2.2.12 on 2020-06-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0065_auto_20200619_1243")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="use_transformer_entities",
            field=models.BooleanField(
                default=False,
                help_text="When selected, the entities will be trained on a better entities recognition model but the training time will be significantly increased",
                verbose_name="Use Transformer Entities",
            ),
        )
    ]
