# Generated by Django 2.2.12 on 2020-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_repositoryqueuetask_ml_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryqueuetask',
            name='end_training',
            field=models.DateTimeField(null=True, verbose_name='end training'),
        ),
    ]
