# Generated by Django 2.2.12 on 2020-07-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200709_1540'),
        ('common', '0069_auto_20200703_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('repositoryowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='authentication.RepositoryOwner')),
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'repository organization',
            },
            bases=('authentication.repositoryowner',),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='authentication.RepositoryOwner'),
        ),
    ]
