# Generated by Django 2.2.12 on 2020-07-10 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_auto_20200709_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='repositoryowner_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.RepositoryOwner'),
        ),
    ]
