# Generated by Django 2.2.12 on 2020-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0070_auto_20200729_1220")]

    operations = [
        migrations.AddIndex(
            model_name="repositorynlplog",
            index=models.Index(
                fields=["repository_version_language", "user"],
                name="common_repo_nlp_log_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryversion",
            index=models.Index(
                fields=["created_by", "repository"],
                name="common_repository_version_idx",
            ),
        ),
    ]
