# Generated by Django 2.2.12 on 2020-07-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_repository_owner'),
        ('common', '0071_auto_20200710_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='repositoryowner_ptr',
        ),
        migrations.AddField(
            model_name='organization',
            name='repository_owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organization_owner', serialize=False, to='authentication.RepositoryOwner'),
            preserve_default=False,
        ),
    ]
