# Generated by Django 2.2.12 on 2020-07-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0071_auto_20200729_1632")]

    operations = [
        migrations.RemoveIndex(
            model_name="repositorynlplog", name="common_repo_nlp_log_idx"
        ),
        migrations.AddIndex(
            model_name="repositorynlplog",
            index=models.Index(
                condition=models.Q(from_backend=False),
                fields=["repository_version_language", "user"],
                name="common_repo_nlp_log_idx",
            ),
        ),
    ]
