# Generated by Django 2.2.12 on 2020-07-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_organizationauthorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauthorization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_authorizations', to='common.Organization'),
        ),
    ]
