# Generated by Django 2.2.12 on 2020-07-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0072_auto_20200710_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.RepositoryOwner'),
        ),
    ]
