# Generated by Django 2.2.12 on 2020-07-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0073_auto_20200717_1100")]

    operations = [
        migrations.AlterField(
            model_name="organizationauthorization",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_user_authorization",
                to="authentication.RepositoryOwner",
            ),
        )
    ]
