# Generated by Django 2.2.12 on 2020-07-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0074_auto_20200717_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verificated',
            field=models.BooleanField(default=False),
        ),
    ]
