# Generated by Django 2.2.12 on 2020-08-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0077_auto_20200807_1410")]

    operations = [
        migrations.AlterModelOptions(
            name="repositorynlplog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "repository nlp logs",
            },
        )
    ]
