# Generated by Django 2.2.12 on 2020-08-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0078_auto_20200807_1425")]

    operations = [
        migrations.AlterField(
            model_name="requestrepositoryauthorization",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.RepositoryOwner",
            ),
        ),
        migrations.AlterField(
            model_name="requestrepositoryauthorization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="authentication.RepositoryOwner",
            ),
        ),
    ]
