# Generated by Django 2.2.12 on 2020-08-19 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migration(apps, schema_editor):  # pragma: no cover
    RepositoryExample = apps.get_model("common", "RepositoryExample")
    RepositoryIntent = apps.get_model("common", "RepositoryIntent")

    for example in RepositoryExample.objects.all():
        if example.repository_version_language is not None and example.old_intent is not None:
            intent, created = RepositoryIntent.objects.get_or_create(
                repository_version=example.repository_version_language.repository_version,
                intent=example.old_intent
            )
            example.intent = intent
            example.save(update_fields=['intent'])


class Migration(migrations.Migration):

    dependencies = [("common", "0079_auto_20200812_1513")]

    operations = [
        migrations.CreateModel(
            name="RepositoryIntent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="no_intent",
                        help_text="Example intent reference",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-z0-9_]+\\Z"),
                                "Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                        verbose_name="intent",
                    ),
                ),
                (
                    "repository_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.RepositoryVersion",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository intent",
                "verbose_name_plural": "repository intents",
            },
        ),
        migrations.RenameField(
            model_name="repositoryexample", old_name="intent", new_name="old_intent"
        ),
        migrations.AddField(
            model_name='repositoryexample',
            name='intent',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='common.RepositoryIntent'),
            preserve_default=False,
        ),
        migrations.RunPython(migration, noop),
        migrations.RemoveField(model_name="repositoryexample", name="old_intent"),
        migrations.AlterUniqueTogether(
            name='repositoryintent',
            unique_together={('repository_version', 'text')},
        ),
    ]
