# Generated by Django 2.2.12 on 2020-08-19 13:36

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0079_auto_20200812_1513")]

    operations = [
        migrations.CreateModel(
            name="RepositoryIntent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="no_intent",
                        help_text="Example intent reference",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-a-z0-9_]+\\Z"),
                                "Enter a valid value consisting of lowercase letters, numbers, underscores or hyphens.",
                                "invalid",
                            )
                        ],
                        verbose_name="intent",
                    ),
                ),
                (
                    "repository_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.RepositoryVersion",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository intent",
                "verbose_name_plural": "repository intents",
            },
        ),
        migrations.RenameField(
            model_name="repositoryexample", old_name="intent", new_name="old_intent"
        ),
        migrations.AddField(
            model_name="repositoryexample",
            name="intent",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.RepositoryIntent",
            ),
            preserve_default=False,
        ),
    ]
