# Generated by Django 2.2.12 on 2020-08-21 15:50

from django.db import migrations
from django.db.models import Q


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migration(apps, schema_editor):  # pragma: no cover
    RepositoryExample = apps.get_model("common", "RepositoryExample")
    RepositoryIntent = apps.get_model("common", "RepositoryIntent")

    chunk = []

    # Delete all rows null that does not belong to any intelligence
    RepositoryExample.objects.filter(
        Q(old_intent__isnull=True) | Q(repository_version_language__isnull=True)
    ).delete()

    for i, example in enumerate(
        RepositoryExample.objects.only(
            "repository_version_language", "old_intent", "intent"
        ).iterator(chunk_size=10000)
    ):
        if (
            example.repository_version_language is not None
            and example.old_intent is not None
        ):
            intent, created = RepositoryIntent.objects.get_or_create(
                repository_version=example.repository_version_language.repository_version,
                text=example.old_intent,
            )
            example.intent = intent
            chunk.append(example)
        if i % 10000 == 0 and chunk:
            RepositoryExample.objects.bulk_update(chunk, ["intent"])
            chunk = []
    if chunk:
        RepositoryExample.objects.bulk_update(chunk, ["intent"])


class Migration(migrations.Migration):

    dependencies = [("common", "0080_repositoryintent")]

    operations = [migrations.RunPython(migration, noop)]
