# Generated by Django 2.2.12 on 2020-08-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0080_repositoryintent")]

    operations = [
        migrations.AlterField(
            model_name="repositoryexample",
            name="intent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.RepositoryIntent",
            ),
        )
    ]
