# Generated by Django 2.2.12 on 2020-08-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0081_auto_20200821_1250")]

    operations = [
        migrations.RemoveField(model_name="repositoryexample", name="old_intent"),
        migrations.AlterField(
            model_name="repositoryexample",
            name="intent",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.RepositoryIntent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repositoryexample",
            name="repository_version_language",
            field=models.ForeignKey(
                default=None,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="added",
                to="common.RepositoryVersionLanguage",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="repositoryintent", unique_together={("repository_version", "text")}
        ),
    ]
