# Generated by Django 2.2.12 on 2020-08-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0082_auto_20200819_1431'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repositoryintent',
            name='intent_valid',
        ),
    ]
