# Generated by Django 2.2.12 on 2020-08-31 18:24

from django.db import migrations


def noop(apps, schema_editor):  # pragma: no cover
    pass


def migration(apps, schema_editor):  # pragma: no cover
    RepositoryVersionLanguage = apps.get_model("common", "RepositoryVersionLanguage")
    RepositoryTranslatedExample = apps.get_model(
        "common", "RepositoryTranslatedExample"
    )

    def get_version_language(repository_version, language):
        version_language, created = RepositoryVersionLanguage.objects.get_or_create(
            repository_version=repository_version, language=language
        )
        return version_language

    chunk = []

    for i, translated in enumerate(
        RepositoryTranslatedExample.objects.only(
            "repository_version_language", "original_example"
        ).iterator(chunk_size=10000)
    ):
        if translated.repository_version_language.language != translated.language:
            repository_version_language = get_version_language(
                translated.original_example.repository_version_language.repository_version,
                translated.language,
            )
            translated.repository_version_language = repository_version_language
            chunk.append(translated)
        if i % 10000 == 0 and chunk:
            RepositoryTranslatedExample.objects.bulk_update(
                chunk, ["repository_version_language"]
            )
            chunk = []
    if chunk:
        RepositoryTranslatedExample.objects.bulk_update(
            chunk, ["repository_version_language"]
        )


class Migration(migrations.Migration):

    dependencies = [("common", "0085_count_repositoryreports")]

    operations = [migrations.RunPython(migration, noop)]
