# Generated by Django 2.2.12 on 2020-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0085_repositoryreports_user")]

    operations = [
        migrations.AlterField(
            model_name="repositoryreports",
            name="report_date",
            field=models.DateField(verbose_name="report date"),
        )
    ]
