# Generated by Django 2.2.16 on 2020-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0086_fix_translations")]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="allow_search_examples",
            field=models.BooleanField(
                default=False, verbose_name="Authorizes third-party phrase search"
            ),
        )
    ]
