# Generated by Django 2.2.16 on 2020-09-30 11:00
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0090_auto_20200921_1751")]

    operations = [UnaccentExtension(), TrigramExtension()]
