# Generated by Django 2.2.16 on 2020-09-29 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_auto_20200729_1220"),
        ("common", "0091_repository_count_authorizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryTranslator",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.RepositoryOwner",
                    ),
                ),
                (
                    "repository_version_language",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator",
                        to="common.RepositoryVersionLanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "repository translator",
                "verbose_name_plural": "repository translators",
            },
        )
    ]
