# Generated by Django 2.2.15 on 2020-09-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0091_extensions"),
        ("common", "0091_repository_count_authorizations"),
    ]

    operations = []
