# Generated by Django 2.2.15 on 2020-10-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0093_repositorytranslator")]

    operations = [
        migrations.AddField(
            model_name="repositoryqueuetask",
            name="type_processing",
            field=models.PositiveIntegerField(
                choices=[(0, "NLP Tranining"), (1, "Repository Auto Translation")],
                default=0,
                verbose_name="Type Processing",
            ),
            preserve_default=False,
        )
    ]
