# Generated by Django 2.2.15 on 2020-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0094_repositoryqueuetask_type_processing")]

    operations = [
        migrations.AlterField(
            model_name="repositoryqueuetask",
            name="from_queue",
            field=models.PositiveIntegerField(
                choices=[(0, "Ai Platform"), (1, "Celery")],
                default=1,
                verbose_name="From Queue NLP",
            ),
        )
    ]
