# Generated by Django 2.2.15 on 2020-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0095_auto_20201001_1944")]

    operations = [
        migrations.AlterField(
            model_name="repositoryqueuetask",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Pending"),
                    (2, "Success"),
                    (1, "Processing"),
                    (3, "Failed"),
                ],
                default=0,
                verbose_name="Status Queue NLP",
            ),
        )
    ]
