# Generated by Django 2.2.16 on 2020-10-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0096_auto_20201001_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intents_balance_score', models.FloatField()),
                ('intents_balance_recommended', models.IntegerField()),
                ('intents_size_score', models.FloatField()),
                ('intents_size_recommended', models.IntegerField()),
                ('evaluate_size_score', models.FloatField()),
                ('evaluate_size_recommended', models.IntegerField()),
                ('repository_score', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='common.Repository')),
            ],
            options={
                'verbose_name': 'repository score',
                'verbose_name_plural': 'repository scores',
            },
        ),
    ]
