# Generated by Django 2.2.16 on 2020-10-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0097_repositoryscore"),
        ("common", "0097_repositorymigrate"),
    ]

    operations = []
