# Generated by Django 2.2.16 on 2020-10-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0097_repositoryscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryscore',
            name='repository_score',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='repository_score', to='common.Repository'),
        ),
    ]
