# Generated by Django 2.2.16 on 2020-10-08 18:34

import bothub.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0097_repositorymigrate")]

    operations = [
        migrations.AddField(
            model_name="repositorymigrate",
            name="classifier",
            field=models.CharField(
                default="wit",
                editable=False,
                max_length=30,
                validators=[bothub.utils.validate_classifier],
                verbose_name="classifier",
            ),
            preserve_default=False,
        )
    ]
