# Generated by Django 2.2.16 on 2020-10-08 18:48

import bothub.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0098_repositorymigrate_classifier")]

    operations = [
        migrations.AlterField(
            model_name="repositorymigrate",
            name="classifier",
            field=models.CharField(
                editable=False,
                max_length=16,
                validators=[bothub.utils.validate_classifier],
                verbose_name="classifier",
            ),
        )
    ]
