# Generated by Django 2.2.16 on 2020-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0098_auto_20201007_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryscore',
            name='evaluate_size_recommended',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repositoryscore',
            name='intents_balance_recommended',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repositoryscore',
            name='intents_size_recommended',
            field=models.TextField(),
        ),
    ]
