# Generated by Django 2.2.16 on 2020-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0099_auto_20201008_1848"),
        ("common", "0098_merge_20201008_1607"),
    ]

    operations = []
