# Generated by Django 2.2.16 on 2020-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_auto_20200729_1220"),
        ("common", "0100_merge_20201009_1739"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="repositoryreports",
            unique_together={("repository_version_language", "user", "report_date")},
        )
    ]
