# Generated by Django 2.2.17 on 2020-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0101_auto_20201020_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryevaluateresult',
            name='automatic',
            field=models.BooleanField(default=False, verbose_name='automatic evaluate'),
        ),
        migrations.AlterField(
            model_name='repositoryqueuetask',
            name='type_processing',
            field=models.PositiveIntegerField(choices=[(0, 'NLP Tranining'), (1, 'Repository Auto Translation'), (1, 'Repository Auto Evaluate')], verbose_name='Type Processing'),
        ),
    ]
