# Generated by Django 2.2.17 on 2020-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0101_auto_20201020_1546")]

    operations = [
        migrations.AddField(
            model_name="repositoryevaluateresult",
            name="cross_validation",
            field=models.BooleanField(default=False, verbose_name="cross validation"),
        )
    ]
