# Generated by Django 2.2.17 on 2021-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0102_repositoryevaluateresult_cross_validation")]

    operations = [
        migrations.AlterField(
            model_name="repositoryqueuetask",
            name="type_processing",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "NLP Tranining"),
                    (1, "Repository Auto Translation"),
                    (2, "Evaluate Cross Validation"),
                ],
                verbose_name="Type Processing",
            ),
        )
    ]
