# Generated by Django 2.2.17 on 2021-03-09 19:39

import bothub.common.languages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("common", "0103_auto_20210302_1431")]

    operations = [
        migrations.CreateModel(
            name="QAKnowledgeBase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Knowledge Base title",
                        max_length=64,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Knowledge Base text", verbose_name="text"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Knowledge Base language",
                        max_length=5,
                        validators=[bothub.common.languages.validate_language],
                        verbose_name="language",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("last_update", models.DateTimeField(verbose_name="last update")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to="common.Repository",
                    ),
                ),
            ],
        )
    ]
