# Generated by Django 2.2.17 on 2021-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0104_qaknowledgebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaknowledgebase',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
    ]
