# Generated by Django 2.2.19 on 2021-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0107_auto_20210311_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('classifier', 'Classifier'), ('content', 'Content')], default='classifier', max_length=50, verbose_name='type'),
        ),
    ]
