# Generated by Django 2.2.22 on 2021-06-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0108_repository_repository_type")]

    operations = [
        migrations.AlterModelOptions(
            name="repositorynlplog",
            options={"ordering": ["-id"], "verbose_name": "repository nlp logs"},
        )
    ]
