# Generated by Django 2.2.22 on 2021-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0109_auto_20210601_0323")]

    operations = [
        migrations.AddIndex(
            model_name="repositoryexample",
            index=models.Index(
                fields=["repository_version_language"],
                name="common_repository_example_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositorytranslatedexample",
            index=models.Index(
                fields=["repository_version_language", "language"],
                name="repository_version_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryversionlanguage",
            index=models.Index(
                fields=["repository_version"], name="vs_repository_version_idx"
            ),
        ),
    ]
