# Generated by Django 3.2.6 on 2021-08-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210506_1453'),
        ('common', '0110_auto_20210601_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='QALogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question')),
                ('user_agent', models.TextField(help_text='User Agent')),
                ('from_backend', models.BooleanField()),
                ('nlp_log', models.JSONField(blank=True, help_text='NLP Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('context', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_nlp_logs', to='common.qacontext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.repositoryowner')),
            ],
            options={
                'verbose_name': 'repository qa nlp logs',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='qalogs',
            index=models.Index(condition=models.Q(('from_backend', False)), fields=['context', 'user'], name='common_repo_qa_nlp_log_idx'),
        ),
    ]
