# Generated by Django 3.2.6 on 2021-09-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0111_auto_20210826_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QAContext',
            new_name='QAtext',
        ),
    ]
