# Generated by Django 3.2.8 on 2021-12-01 13:30

import django.core.validators
from django.db import migrations, models
import re


VALIDATE_REGEX = ".[-a-zA-Z_]"
VALIDATE_TEXT = "Enter a valid value that have letters in it"


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0111_auto_20210908_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qatext",
            name="text",
            field=models.TextField(
                help_text="QA context text",
                max_length=25000,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(VALIDATE_REGEX),
                        VALIDATE_TEXT,
                        "invalid",
                    )
                ],
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="repositoryexample",
            name="text",
            field=models.TextField(
                help_text="Example text",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(VALIDATE_REGEX),
                        VALIDATE_TEXT,
                        "invalid",
                    )
                ],
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="repositorytranslatedexample",
            name="text",
            field=models.TextField(
                help_text="Translation text",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(VALIDATE_REGEX),
                        VALIDATE_TEXT,
                        "invalid",
                    )
                ],
                verbose_name="text",
            ),
        ),
    ]
