# Generated by Django 3.2.8 on 2022-02-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0112_auto_20211201_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qatext",
            name="text",
            field=models.TextField(
                help_text="QA context text", max_length=25000, verbose_name="text"
            ),
        ),
        migrations.AlterField(
            model_name="repositoryexample",
            name="text",
            field=models.TextField(help_text="Example text", verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="repositorytranslatedexample",
            name="text",
            field=models.TextField(help_text="Translation text", verbose_name="text"),
        ),
    ]
