# Generated by Django 3.2.6 on 2021-09-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0112_rename_qacontext_qatext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qatext',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='common.qaknowledgebase'),
        ),
    ]
