# Generated by Django 3.2.12 on 2022-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0113_auto_20220216_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repositoryversionlanguage',
            unique_together={('language', 'repository_version')},
        ),
    ]
