# Generated by Django 3.2.15 on 2022-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0114_alter_repositoryversionlanguage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'user'), (2, 'contributor'), (3, 'admin')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='repositoryauthorization',
            name='role',
            field=models.PositiveIntegerField(choices=[(0, 'not set'), (1, 'user'), (2, 'contributor'), (3, 'admin')], default=0, verbose_name='role'),
        ),
    ]
