# Generated by Django 3.2.15 on 2023-06-16 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0117_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('4e33306e-3f43-4dad-9bc6-fc5e4c1703a8')),
        ),
    ]
