# Generated by Django 3.2.15 on 2023-05-16 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0117_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryevaluate',
            name='evaluate_type',
            field=models.PositiveIntegerField(choices=[(0, 'manual'), (1, 'automatic')], default=0, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='repositoryzeroshot',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ended at'),
        ),
        migrations.AlterField(
            model_name='repositoryzeroshot',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, related_name='repository_options', to='common.ZeroShotOptionsText'),
        ),
        migrations.AlterField(
            model_name='repositoryzeroshot',
            name='zeroshot_log',
            field=models.TextField(blank=True, help_text='NLP Log', null=True),
        ),
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('fad96a44-5d34-4eb6-9d91-99dc8b2de924')),
        ),
    ]
