# Generated by Django 3.2.15 on 2023-05-17 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0117_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('c3decab1-a30d-4b06-acb4-406920f7c557')),
        ),
    ]
