# Generated by Django 3.2.15 on 2023-05-16 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_auto_20230516_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryevaluate',
            name='evaluate_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'manual'), (1, 'automatic')], default=0, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('7d6362d2-5720-47ba-b4fc-0accffff52df')),
        ),
    ]
