# Generated by Django 3.2.15 on 2023-05-17 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('9435d2ca-821d-4a11-bff2-082ba91f04dc')),
        ),
    ]
