# Generated by Django 3.2.15 on 2023-06-17 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('f9b22f20-a55c-4864-8c32-b09bf2d7b4ef')),
        ),
    ]
