# Generated by Django 3.2.21 on 2023-10-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0120_auto_20231016_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroshotlogs',
            name='language',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Language'),
        ),
    ]
