# Generated by Django 3.2.15 on 2023-05-17 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0120_alter_zeroshotoptions_option_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryzeroshot',
            name='options',
        ),
        migrations.AddField(
            model_name='repositoryzeroshot',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repository_options', to='common.zeroshotoptions'),
        ),
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('8c344d9b-05be-43b6-8e65-c60debdbacbc')),
        ),
        migrations.AlterField(
            model_name='zeroshotoptionstext',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_key', to='common.zeroshotoptions'),
        ),
    ]
