# Generated by Django 3.2.15 on 2023-05-17 14:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0121_auto_20230517_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryzeroshot',
            name='options',
        ),
        migrations.AddField(
            model_name='zeroshotoptions',
            name='repository_zeroshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repository_options', to='common.repositoryzeroshot'),
        ),
        migrations.AlterField(
            model_name='zeroshotoptions',
            name='option_uuid',
            field=models.UUIDField(default=uuid.UUID('f556d4d5-9a65-46ec-9231-72e3c443776c')),
        ),
    ]
