# Generated by Django 3.2.21 on 2023-12-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0121_zeroshotlogs_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zeroshotlogs',
            old_name='categories',
            new_name='options',
        ),
    ]
