# Generated by Django 3.2.15 on 2023-05-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0118_auto_20230517_1711'),
        ('common', '0122_auto_20230517_1430'),
    ]

    operations = [
    ]
